language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install -e .
  - pip install pytest pytest-cov coveralls
script:
  - pytest --cov mudslide
after_success:
  coveralls
